// Code generated by ent, DO NOT EDIT.

package relationtuple

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the relationtuple type in the database.
	Label = "relation_tuple"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldRelation holds the string denoting the relation field in the database.
	FieldRelation = "relation"
	// FieldObject holds the string denoting the object field in the database.
	FieldObject = "object"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the relationtuple in the database.
	Table = "relation_tuples"
)

// Columns holds all SQL columns for relationtuple fields.
var Columns = []string{
	FieldID,
	FieldSubject,
	FieldRelation,
	FieldObject,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	SubjectValidator func(string) error
	// RelationValidator is a validator for the "relation" field. It is called by the builders before save.
	RelationValidator func(string) error
	// ObjectValidator is a validator for the "object" field. It is called by the builders before save.
	ObjectValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the RelationTuple queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// ByRelation orders the results by the relation field.
func ByRelation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelation, opts...).ToFunc()
}

// ByObject orders the results by the object field.
func ByObject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObject, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
