// Code generated by ent, DO NOT EDIT.

package relationtuple

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/plma-jshs/iam-server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldLTE(FieldID, id))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldEQ(FieldSubject, v))
}

// Relation applies equality check predicate on the "relation" field. It's identical to RelationEQ.
func Relation(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldEQ(FieldRelation, v))
}

// Object applies equality check predicate on the "object" field. It's identical to ObjectEQ.
func Object(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldEQ(FieldObject, v))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldEQ(FieldCreatedAt, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldContainsFold(FieldSubject, v))
}

// RelationEQ applies the EQ predicate on the "relation" field.
func RelationEQ(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldEQ(FieldRelation, v))
}

// RelationNEQ applies the NEQ predicate on the "relation" field.
func RelationNEQ(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldNEQ(FieldRelation, v))
}

// RelationIn applies the In predicate on the "relation" field.
func RelationIn(vs ...string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldIn(FieldRelation, vs...))
}

// RelationNotIn applies the NotIn predicate on the "relation" field.
func RelationNotIn(vs ...string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldNotIn(FieldRelation, vs...))
}

// RelationGT applies the GT predicate on the "relation" field.
func RelationGT(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldGT(FieldRelation, v))
}

// RelationGTE applies the GTE predicate on the "relation" field.
func RelationGTE(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldGTE(FieldRelation, v))
}

// RelationLT applies the LT predicate on the "relation" field.
func RelationLT(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldLT(FieldRelation, v))
}

// RelationLTE applies the LTE predicate on the "relation" field.
func RelationLTE(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldLTE(FieldRelation, v))
}

// RelationContains applies the Contains predicate on the "relation" field.
func RelationContains(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldContains(FieldRelation, v))
}

// RelationHasPrefix applies the HasPrefix predicate on the "relation" field.
func RelationHasPrefix(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldHasPrefix(FieldRelation, v))
}

// RelationHasSuffix applies the HasSuffix predicate on the "relation" field.
func RelationHasSuffix(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldHasSuffix(FieldRelation, v))
}

// RelationEqualFold applies the EqualFold predicate on the "relation" field.
func RelationEqualFold(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldEqualFold(FieldRelation, v))
}

// RelationContainsFold applies the ContainsFold predicate on the "relation" field.
func RelationContainsFold(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldContainsFold(FieldRelation, v))
}

// ObjectEQ applies the EQ predicate on the "object" field.
func ObjectEQ(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldEQ(FieldObject, v))
}

// ObjectNEQ applies the NEQ predicate on the "object" field.
func ObjectNEQ(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldNEQ(FieldObject, v))
}

// ObjectIn applies the In predicate on the "object" field.
func ObjectIn(vs ...string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldIn(FieldObject, vs...))
}

// ObjectNotIn applies the NotIn predicate on the "object" field.
func ObjectNotIn(vs ...string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldNotIn(FieldObject, vs...))
}

// ObjectGT applies the GT predicate on the "object" field.
func ObjectGT(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldGT(FieldObject, v))
}

// ObjectGTE applies the GTE predicate on the "object" field.
func ObjectGTE(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldGTE(FieldObject, v))
}

// ObjectLT applies the LT predicate on the "object" field.
func ObjectLT(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldLT(FieldObject, v))
}

// ObjectLTE applies the LTE predicate on the "object" field.
func ObjectLTE(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldLTE(FieldObject, v))
}

// ObjectContains applies the Contains predicate on the "object" field.
func ObjectContains(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldContains(FieldObject, v))
}

// ObjectHasPrefix applies the HasPrefix predicate on the "object" field.
func ObjectHasPrefix(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldHasPrefix(FieldObject, v))
}

// ObjectHasSuffix applies the HasSuffix predicate on the "object" field.
func ObjectHasSuffix(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldHasSuffix(FieldObject, v))
}

// ObjectEqualFold applies the EqualFold predicate on the "object" field.
func ObjectEqualFold(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldEqualFold(FieldObject, v))
}

// ObjectContainsFold applies the ContainsFold predicate on the "object" field.
func ObjectContainsFold(v string) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldContainsFold(FieldObject, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.RelationTuple {
	return predicate.RelationTuple(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RelationTuple) predicate.RelationTuple {
	return predicate.RelationTuple(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RelationTuple) predicate.RelationTuple {
	return predicate.RelationTuple(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RelationTuple) predicate.RelationTuple {
	return predicate.RelationTuple(sql.NotPredicates(p))
}
