// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RelationTuplesColumns holds the columns for the "relation_tuples" table.
	RelationTuplesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "subject", Type: field.TypeString},
		{Name: "relation", Type: field.TypeString},
		{Name: "object", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// RelationTuplesTable holds the schema information for the "relation_tuples" table.
	RelationTuplesTable = &schema.Table{
		Name:       "relation_tuples",
		Columns:    RelationTuplesColumns,
		PrimaryKey: []*schema.Column{RelationTuplesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RelationTuplesTable,
	}
)

func init() {
}
