// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/plma-jshs/iam-server/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/plma-jshs/iam-server/ent/relationtuple"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// RelationTuple is the client for interacting with the RelationTuple builders.
	RelationTuple *RelationTupleClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.RelationTuple = NewRelationTupleClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		RelationTuple: NewRelationTupleClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		RelationTuple: NewRelationTupleClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		RelationTuple.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.RelationTuple.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.RelationTuple.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *RelationTupleMutation:
		return c.RelationTuple.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// RelationTupleClient is a client for the RelationTuple schema.
type RelationTupleClient struct {
	config
}

// NewRelationTupleClient returns a client for the RelationTuple from the given config.
func NewRelationTupleClient(c config) *RelationTupleClient {
	return &RelationTupleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `relationtuple.Hooks(f(g(h())))`.
func (c *RelationTupleClient) Use(hooks ...Hook) {
	c.hooks.RelationTuple = append(c.hooks.RelationTuple, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `relationtuple.Intercept(f(g(h())))`.
func (c *RelationTupleClient) Intercept(interceptors ...Interceptor) {
	c.inters.RelationTuple = append(c.inters.RelationTuple, interceptors...)
}

// Create returns a builder for creating a RelationTuple entity.
func (c *RelationTupleClient) Create() *RelationTupleCreate {
	mutation := newRelationTupleMutation(c.config, OpCreate)
	return &RelationTupleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RelationTuple entities.
func (c *RelationTupleClient) CreateBulk(builders ...*RelationTupleCreate) *RelationTupleCreateBulk {
	return &RelationTupleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RelationTupleClient) MapCreateBulk(slice any, setFunc func(*RelationTupleCreate, int)) *RelationTupleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RelationTupleCreateBulk{err: fmt.Errorf("calling to RelationTupleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RelationTupleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RelationTupleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RelationTuple.
func (c *RelationTupleClient) Update() *RelationTupleUpdate {
	mutation := newRelationTupleMutation(c.config, OpUpdate)
	return &RelationTupleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RelationTupleClient) UpdateOne(_m *RelationTuple) *RelationTupleUpdateOne {
	mutation := newRelationTupleMutation(c.config, OpUpdateOne, withRelationTuple(_m))
	return &RelationTupleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RelationTupleClient) UpdateOneID(id int) *RelationTupleUpdateOne {
	mutation := newRelationTupleMutation(c.config, OpUpdateOne, withRelationTupleID(id))
	return &RelationTupleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RelationTuple.
func (c *RelationTupleClient) Delete() *RelationTupleDelete {
	mutation := newRelationTupleMutation(c.config, OpDelete)
	return &RelationTupleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RelationTupleClient) DeleteOne(_m *RelationTuple) *RelationTupleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RelationTupleClient) DeleteOneID(id int) *RelationTupleDeleteOne {
	builder := c.Delete().Where(relationtuple.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RelationTupleDeleteOne{builder}
}

// Query returns a query builder for RelationTuple.
func (c *RelationTupleClient) Query() *RelationTupleQuery {
	return &RelationTupleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRelationTuple},
		inters: c.Interceptors(),
	}
}

// Get returns a RelationTuple entity by its id.
func (c *RelationTupleClient) Get(ctx context.Context, id int) (*RelationTuple, error) {
	return c.Query().Where(relationtuple.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RelationTupleClient) GetX(ctx context.Context, id int) *RelationTuple {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RelationTupleClient) Hooks() []Hook {
	return c.hooks.RelationTuple
}

// Interceptors returns the client interceptors.
func (c *RelationTupleClient) Interceptors() []Interceptor {
	return c.inters.RelationTuple
}

func (c *RelationTupleClient) mutate(ctx context.Context, m *RelationTupleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RelationTupleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RelationTupleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RelationTupleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RelationTupleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RelationTuple mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		RelationTuple []ent.Hook
	}
	inters struct {
		RelationTuple []ent.Interceptor
	}
)
