// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/plma-jshs/iam-server/ent/predicate"
	"github.com/plma-jshs/iam-server/ent/relationtuple"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeRelationTuple = "RelationTuple"
)

// RelationTupleMutation represents an operation that mutates the RelationTuple nodes in the graph.
type RelationTupleMutation struct {
	config
	op            Op
	typ           string
	id            *int
	subject       *string
	relation      *string
	object        *string
	createdAt     *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*RelationTuple, error)
	predicates    []predicate.RelationTuple
}

var _ ent.Mutation = (*RelationTupleMutation)(nil)

// relationtupleOption allows management of the mutation configuration using functional options.
type relationtupleOption func(*RelationTupleMutation)

// newRelationTupleMutation creates new mutation for the RelationTuple entity.
func newRelationTupleMutation(c config, op Op, opts ...relationtupleOption) *RelationTupleMutation {
	m := &RelationTupleMutation{
		config:        c,
		op:            op,
		typ:           TypeRelationTuple,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRelationTupleID sets the ID field of the mutation.
func withRelationTupleID(id int) relationtupleOption {
	return func(m *RelationTupleMutation) {
		var (
			err   error
			once  sync.Once
			value *RelationTuple
		)
		m.oldValue = func(ctx context.Context) (*RelationTuple, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().RelationTuple.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRelationTuple sets the old RelationTuple of the mutation.
func withRelationTuple(node *RelationTuple) relationtupleOption {
	return func(m *RelationTupleMutation) {
		m.oldValue = func(context.Context) (*RelationTuple, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RelationTupleMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RelationTupleMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RelationTupleMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RelationTupleMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().RelationTuple.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetSubject sets the "subject" field.
func (m *RelationTupleMutation) SetSubject(s string) {
	m.subject = &s
}

// Subject returns the value of the "subject" field in the mutation.
func (m *RelationTupleMutation) Subject() (r string, exists bool) {
	v := m.subject
	if v == nil {
		return
	}
	return *v, true
}

// OldSubject returns the old "subject" field's value of the RelationTuple entity.
// If the RelationTuple object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RelationTupleMutation) OldSubject(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSubject is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSubject requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSubject: %w", err)
	}
	return oldValue.Subject, nil
}

// ResetSubject resets all changes to the "subject" field.
func (m *RelationTupleMutation) ResetSubject() {
	m.subject = nil
}

// SetRelation sets the "relation" field.
func (m *RelationTupleMutation) SetRelation(s string) {
	m.relation = &s
}

// Relation returns the value of the "relation" field in the mutation.
func (m *RelationTupleMutation) Relation() (r string, exists bool) {
	v := m.relation
	if v == nil {
		return
	}
	return *v, true
}

// OldRelation returns the old "relation" field's value of the RelationTuple entity.
// If the RelationTuple object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RelationTupleMutation) OldRelation(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRelation is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRelation requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRelation: %w", err)
	}
	return oldValue.Relation, nil
}

// ResetRelation resets all changes to the "relation" field.
func (m *RelationTupleMutation) ResetRelation() {
	m.relation = nil
}

// SetObject sets the "object" field.
func (m *RelationTupleMutation) SetObject(s string) {
	m.object = &s
}

// Object returns the value of the "object" field in the mutation.
func (m *RelationTupleMutation) Object() (r string, exists bool) {
	v := m.object
	if v == nil {
		return
	}
	return *v, true
}

// OldObject returns the old "object" field's value of the RelationTuple entity.
// If the RelationTuple object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RelationTupleMutation) OldObject(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldObject is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldObject requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldObject: %w", err)
	}
	return oldValue.Object, nil
}

// ResetObject resets all changes to the "object" field.
func (m *RelationTupleMutation) ResetObject() {
	m.object = nil
}

// SetCreatedAt sets the "createdAt" field.
func (m *RelationTupleMutation) SetCreatedAt(t time.Time) {
	m.createdAt = &t
}

// CreatedAt returns the value of the "createdAt" field in the mutation.
func (m *RelationTupleMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.createdAt
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "createdAt" field's value of the RelationTuple entity.
// If the RelationTuple object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RelationTupleMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "createdAt" field.
func (m *RelationTupleMutation) ResetCreatedAt() {
	m.createdAt = nil
}

// Where appends a list predicates to the RelationTupleMutation builder.
func (m *RelationTupleMutation) Where(ps ...predicate.RelationTuple) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RelationTupleMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RelationTupleMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.RelationTuple, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RelationTupleMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RelationTupleMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (RelationTuple).
func (m *RelationTupleMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RelationTupleMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.subject != nil {
		fields = append(fields, relationtuple.FieldSubject)
	}
	if m.relation != nil {
		fields = append(fields, relationtuple.FieldRelation)
	}
	if m.object != nil {
		fields = append(fields, relationtuple.FieldObject)
	}
	if m.createdAt != nil {
		fields = append(fields, relationtuple.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RelationTupleMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case relationtuple.FieldSubject:
		return m.Subject()
	case relationtuple.FieldRelation:
		return m.Relation()
	case relationtuple.FieldObject:
		return m.Object()
	case relationtuple.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RelationTupleMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case relationtuple.FieldSubject:
		return m.OldSubject(ctx)
	case relationtuple.FieldRelation:
		return m.OldRelation(ctx)
	case relationtuple.FieldObject:
		return m.OldObject(ctx)
	case relationtuple.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown RelationTuple field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RelationTupleMutation) SetField(name string, value ent.Value) error {
	switch name {
	case relationtuple.FieldSubject:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSubject(v)
		return nil
	case relationtuple.FieldRelation:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRelation(v)
		return nil
	case relationtuple.FieldObject:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetObject(v)
		return nil
	case relationtuple.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown RelationTuple field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RelationTupleMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RelationTupleMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RelationTupleMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown RelationTuple numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RelationTupleMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RelationTupleMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RelationTupleMutation) ClearField(name string) error {
	return fmt.Errorf("unknown RelationTuple nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RelationTupleMutation) ResetField(name string) error {
	switch name {
	case relationtuple.FieldSubject:
		m.ResetSubject()
		return nil
	case relationtuple.FieldRelation:
		m.ResetRelation()
		return nil
	case relationtuple.FieldObject:
		m.ResetObject()
		return nil
	case relationtuple.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown RelationTuple field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RelationTupleMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RelationTupleMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RelationTupleMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RelationTupleMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RelationTupleMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RelationTupleMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RelationTupleMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown RelationTuple unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RelationTupleMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown RelationTuple edge %s", name)
}
