// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plma-jshs/iam-server/ent/predicate"
	"github.com/plma-jshs/iam-server/ent/relationtuple"
)

// RelationTupleUpdate is the builder for updating RelationTuple entities.
type RelationTupleUpdate struct {
	config
	hooks    []Hook
	mutation *RelationTupleMutation
}

// Where appends a list predicates to the RelationTupleUpdate builder.
func (_u *RelationTupleUpdate) Where(ps ...predicate.RelationTuple) *RelationTupleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSubject sets the "subject" field.
func (_u *RelationTupleUpdate) SetSubject(v string) *RelationTupleUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *RelationTupleUpdate) SetNillableSubject(v *string) *RelationTupleUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetRelation sets the "relation" field.
func (_u *RelationTupleUpdate) SetRelation(v string) *RelationTupleUpdate {
	_u.mutation.SetRelation(v)
	return _u
}

// SetNillableRelation sets the "relation" field if the given value is not nil.
func (_u *RelationTupleUpdate) SetNillableRelation(v *string) *RelationTupleUpdate {
	if v != nil {
		_u.SetRelation(*v)
	}
	return _u
}

// SetObject sets the "object" field.
func (_u *RelationTupleUpdate) SetObject(v string) *RelationTupleUpdate {
	_u.mutation.SetObject(v)
	return _u
}

// SetNillableObject sets the "object" field if the given value is not nil.
func (_u *RelationTupleUpdate) SetNillableObject(v *string) *RelationTupleUpdate {
	if v != nil {
		_u.SetObject(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *RelationTupleUpdate) SetCreatedAt(v time.Time) *RelationTupleUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *RelationTupleUpdate) SetNillableCreatedAt(v *time.Time) *RelationTupleUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the RelationTupleMutation object of the builder.
func (_u *RelationTupleUpdate) Mutation() *RelationTupleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RelationTupleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelationTupleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RelationTupleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelationTupleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelationTupleUpdate) check() error {
	if v, ok := _u.mutation.Subject(); ok {
		if err := relationtuple.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "RelationTuple.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Relation(); ok {
		if err := relationtuple.RelationValidator(v); err != nil {
			return &ValidationError{Name: "relation", err: fmt.Errorf(`ent: validator failed for field "RelationTuple.relation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Object(); ok {
		if err := relationtuple.ObjectValidator(v); err != nil {
			return &ValidationError{Name: "object", err: fmt.Errorf(`ent: validator failed for field "RelationTuple.object": %w`, err)}
		}
	}
	return nil
}

func (_u *RelationTupleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relationtuple.Table, relationtuple.Columns, sqlgraph.NewFieldSpec(relationtuple.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(relationtuple.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Relation(); ok {
		_spec.SetField(relationtuple.FieldRelation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Object(); ok {
		_spec.SetField(relationtuple.FieldObject, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(relationtuple.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relationtuple.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RelationTupleUpdateOne is the builder for updating a single RelationTuple entity.
type RelationTupleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RelationTupleMutation
}

// SetSubject sets the "subject" field.
func (_u *RelationTupleUpdateOne) SetSubject(v string) *RelationTupleUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *RelationTupleUpdateOne) SetNillableSubject(v *string) *RelationTupleUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetRelation sets the "relation" field.
func (_u *RelationTupleUpdateOne) SetRelation(v string) *RelationTupleUpdateOne {
	_u.mutation.SetRelation(v)
	return _u
}

// SetNillableRelation sets the "relation" field if the given value is not nil.
func (_u *RelationTupleUpdateOne) SetNillableRelation(v *string) *RelationTupleUpdateOne {
	if v != nil {
		_u.SetRelation(*v)
	}
	return _u
}

// SetObject sets the "object" field.
func (_u *RelationTupleUpdateOne) SetObject(v string) *RelationTupleUpdateOne {
	_u.mutation.SetObject(v)
	return _u
}

// SetNillableObject sets the "object" field if the given value is not nil.
func (_u *RelationTupleUpdateOne) SetNillableObject(v *string) *RelationTupleUpdateOne {
	if v != nil {
		_u.SetObject(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *RelationTupleUpdateOne) SetCreatedAt(v time.Time) *RelationTupleUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *RelationTupleUpdateOne) SetNillableCreatedAt(v *time.Time) *RelationTupleUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the RelationTupleMutation object of the builder.
func (_u *RelationTupleUpdateOne) Mutation() *RelationTupleMutation {
	return _u.mutation
}

// Where appends a list predicates to the RelationTupleUpdate builder.
func (_u *RelationTupleUpdateOne) Where(ps ...predicate.RelationTuple) *RelationTupleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RelationTupleUpdateOne) Select(field string, fields ...string) *RelationTupleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RelationTuple entity.
func (_u *RelationTupleUpdateOne) Save(ctx context.Context) (*RelationTuple, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelationTupleUpdateOne) SaveX(ctx context.Context) *RelationTuple {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RelationTupleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelationTupleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelationTupleUpdateOne) check() error {
	if v, ok := _u.mutation.Subject(); ok {
		if err := relationtuple.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "RelationTuple.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Relation(); ok {
		if err := relationtuple.RelationValidator(v); err != nil {
			return &ValidationError{Name: "relation", err: fmt.Errorf(`ent: validator failed for field "RelationTuple.relation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Object(); ok {
		if err := relationtuple.ObjectValidator(v); err != nil {
			return &ValidationError{Name: "object", err: fmt.Errorf(`ent: validator failed for field "RelationTuple.object": %w`, err)}
		}
	}
	return nil
}

func (_u *RelationTupleUpdateOne) sqlSave(ctx context.Context) (_node *RelationTuple, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relationtuple.Table, relationtuple.Columns, sqlgraph.NewFieldSpec(relationtuple.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RelationTuple.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, relationtuple.FieldID)
		for _, f := range fields {
			if !relationtuple.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != relationtuple.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(relationtuple.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Relation(); ok {
		_spec.SetField(relationtuple.FieldRelation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Object(); ok {
		_spec.SetField(relationtuple.FieldObject, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(relationtuple.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &RelationTuple{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relationtuple.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
