// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/plma-jshs/iam-server/ent/relationtuple"
)

// RelationTuple is the model entity for the RelationTuple schema.
type RelationTuple struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Subject holds the value of the "subject" field.
	Subject string `json:"subject,omitempty"`
	// Relation holds the value of the "relation" field.
	Relation string `json:"relation,omitempty"`
	// Object holds the value of the "object" field.
	Object string `json:"object,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt    time.Time `json:"createdAt,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RelationTuple) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case relationtuple.FieldID:
			values[i] = new(sql.NullInt64)
		case relationtuple.FieldSubject, relationtuple.FieldRelation, relationtuple.FieldObject:
			values[i] = new(sql.NullString)
		case relationtuple.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RelationTuple fields.
func (_m *RelationTuple) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case relationtuple.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case relationtuple.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				_m.Subject = value.String
			}
		case relationtuple.FieldRelation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field relation", values[i])
			} else if value.Valid {
				_m.Relation = value.String
			}
		case relationtuple.FieldObject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field object", values[i])
			} else if value.Valid {
				_m.Object = value.String
			}
		case relationtuple.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RelationTuple.
// This includes values selected through modifiers, order, etc.
func (_m *RelationTuple) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RelationTuple.
// Note that you need to call RelationTuple.Unwrap() before calling this method if this RelationTuple
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RelationTuple) Update() *RelationTupleUpdateOne {
	return NewRelationTupleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RelationTuple entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RelationTuple) Unwrap() *RelationTuple {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RelationTuple is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RelationTuple) String() string {
	var builder strings.Builder
	builder.WriteString("RelationTuple(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("subject=")
	builder.WriteString(_m.Subject)
	builder.WriteString(", ")
	builder.WriteString("relation=")
	builder.WriteString(_m.Relation)
	builder.WriteString(", ")
	builder.WriteString("object=")
	builder.WriteString(_m.Object)
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RelationTuples is a parsable slice of RelationTuple.
type RelationTuples []*RelationTuple
