// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plma-jshs/iam-server/ent/relationtuple"
)

// RelationTupleCreate is the builder for creating a RelationTuple entity.
type RelationTupleCreate struct {
	config
	mutation *RelationTupleMutation
	hooks    []Hook
}

// SetSubject sets the "subject" field.
func (_c *RelationTupleCreate) SetSubject(v string) *RelationTupleCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetRelation sets the "relation" field.
func (_c *RelationTupleCreate) SetRelation(v string) *RelationTupleCreate {
	_c.mutation.SetRelation(v)
	return _c
}

// SetObject sets the "object" field.
func (_c *RelationTupleCreate) SetObject(v string) *RelationTupleCreate {
	_c.mutation.SetObject(v)
	return _c
}

// SetCreatedAt sets the "createdAt" field.
func (_c *RelationTupleCreate) SetCreatedAt(v time.Time) *RelationTupleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_c *RelationTupleCreate) SetNillableCreatedAt(v *time.Time) *RelationTupleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the RelationTupleMutation object of the builder.
func (_c *RelationTupleCreate) Mutation() *RelationTupleMutation {
	return _c.mutation
}

// Save creates the RelationTuple in the database.
func (_c *RelationTupleCreate) Save(ctx context.Context) (*RelationTuple, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RelationTupleCreate) SaveX(ctx context.Context) *RelationTuple {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelationTupleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelationTupleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RelationTupleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := relationtuple.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RelationTupleCreate) check() error {
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "RelationTuple.subject"`)}
	}
	if v, ok := _c.mutation.Subject(); ok {
		if err := relationtuple.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "RelationTuple.subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Relation(); !ok {
		return &ValidationError{Name: "relation", err: errors.New(`ent: missing required field "RelationTuple.relation"`)}
	}
	if v, ok := _c.mutation.Relation(); ok {
		if err := relationtuple.RelationValidator(v); err != nil {
			return &ValidationError{Name: "relation", err: fmt.Errorf(`ent: validator failed for field "RelationTuple.relation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Object(); !ok {
		return &ValidationError{Name: "object", err: errors.New(`ent: missing required field "RelationTuple.object"`)}
	}
	if v, ok := _c.mutation.Object(); ok {
		if err := relationtuple.ObjectValidator(v); err != nil {
			return &ValidationError{Name: "object", err: fmt.Errorf(`ent: validator failed for field "RelationTuple.object": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "RelationTuple.createdAt"`)}
	}
	return nil
}

func (_c *RelationTupleCreate) sqlSave(ctx context.Context) (*RelationTuple, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RelationTupleCreate) createSpec() (*RelationTuple, *sqlgraph.CreateSpec) {
	var (
		_node = &RelationTuple{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(relationtuple.Table, sqlgraph.NewFieldSpec(relationtuple.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(relationtuple.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.Relation(); ok {
		_spec.SetField(relationtuple.FieldRelation, field.TypeString, value)
		_node.Relation = value
	}
	if value, ok := _c.mutation.Object(); ok {
		_spec.SetField(relationtuple.FieldObject, field.TypeString, value)
		_node.Object = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(relationtuple.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// RelationTupleCreateBulk is the builder for creating many RelationTuple entities in bulk.
type RelationTupleCreateBulk struct {
	config
	err      error
	builders []*RelationTupleCreate
}

// Save creates the RelationTuple entities in the database.
func (_c *RelationTupleCreateBulk) Save(ctx context.Context) ([]*RelationTuple, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RelationTuple, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RelationTupleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RelationTupleCreateBulk) SaveX(ctx context.Context) []*RelationTuple {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelationTupleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelationTupleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
