// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/plma-jshs/iam-server/ent/relationtuple"
	"github.com/plma-jshs/iam-server/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	relationtupleFields := schema.RelationTuple{}.Fields()
	_ = relationtupleFields
	// relationtupleDescSubject is the schema descriptor for subject field.
	relationtupleDescSubject := relationtupleFields[0].Descriptor()
	// relationtuple.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	relationtuple.SubjectValidator = relationtupleDescSubject.Validators[0].(func(string) error)
	// relationtupleDescRelation is the schema descriptor for relation field.
	relationtupleDescRelation := relationtupleFields[1].Descriptor()
	// relationtuple.RelationValidator is a validator for the "relation" field. It is called by the builders before save.
	relationtuple.RelationValidator = relationtupleDescRelation.Validators[0].(func(string) error)
	// relationtupleDescObject is the schema descriptor for object field.
	relationtupleDescObject := relationtupleFields[2].Descriptor()
	// relationtuple.ObjectValidator is a validator for the "object" field. It is called by the builders before save.
	relationtuple.ObjectValidator = relationtupleDescObject.Validators[0].(func(string) error)
	// relationtupleDescCreatedAt is the schema descriptor for createdAt field.
	relationtupleDescCreatedAt := relationtupleFields[3].Descriptor()
	// relationtuple.DefaultCreatedAt holds the default value on creation for the createdAt field.
	relationtuple.DefaultCreatedAt = relationtupleDescCreatedAt.Default.(func() time.Time)
}
