name: CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Build and Test
        run: |
          go build -o iam-server.exe ./cmd/server
          go test -v ./...

      - name: Deploy Firmware
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PLMA_REMOTE_HOST }}
          username: ${{ secrets.PLMA_REMOTE_USER }}
          key: ${{ secrets.PLMA_SSH_PRIVATE_KEY }}
          port: ${{ secrets.PLMA_REMOTE_PORT }}
          source: "iam-server.exe"
          target: "/tmp"
