name: CI

on:
  pull_request:
    branches: [main, rc]

permissions:
  contents: read

jobs:
  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Run golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: "--timeout=5m"
          reporter: github-pr-review
