name: NAMESPACE VALIDATION
on:
  push:
    branches: [main, rc]
    paths:
      - "namespaces/**"
      - "**.zed"
  pull_request:
    branches: [main, rc]
    paths:
      - "schema/**"
      - "**.zed"
jobs:
  validate-namespace:
    runs-on: ubuntu-latest
    container:
      image: authzed/zed:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Validate Schema Folder
        run: zed validate namespaces/
