name: NAMESPACE VALIDATION
on:
  push:
    branches: [main, rc]
    paths:
      - "namespaces/**"
      - "**.zed"
  pull_request:
    branches: [main, rc]
    paths:
      - "schema/**"
      - "**.zed"
jobs:
  validate-namespace:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install SpiceDB CLI
        run: |
          curl -sSL https://github.com/authzed/zed/releases/latest/download/zed_linux_amd64.tar.gz -o zed.tar.gz

          tar -xzf zed.tar.gz

          chmod +x zed
          sudo mv zed /usr/local/bin/zed

      - name: Validate Namespace
        run: |
          zed version
          zed validate namespaces/
