name: NAMESPACE VALIDATION
on:
  push:
    branches: [main, rc]
    paths:
      - "namespaces/**"
      - "**.zed"
  pull_request:
    branches: [main, rc]
    paths:
      - "schema/**"
      - "**.zed"
jobs:
  validate-namespace:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install SpiceDB CLI
        run: |
          curl -sSL https://authzed.com/install.sh | sh -s -- -b /usr/local/bin

      - name: Validate Namespace
        run: zed validate namespaces/
