// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// RelationTuple is the predicate function for relationtuple builders.
type RelationTuple func(*sql.Selector)
